MORPHEUS_CFG_DEPENDS(TPLS OPTIONS)
MORPHEUS_CFG_DEPENDS(TPLS DEVICES)
MORPHEUS_CFG_DEPENDS(TPLS COMPILER_ID)

FUNCTION(MORPHEUS_TPL_OPTION PKG DEFAULT)
  CMAKE_PARSE_ARGUMENTS(PARSED
    ""
    "TRIBITS"
    ""
    ${ARGN})

  IF (PARSED_TRIBITS)
    #this is also a TPL option you can activate with Tribits
    IF (NOT "${TPL_ENABLE_${PARSED_TRIBITS}}" STREQUAL "")
      #Tribits brought its own default that should take precedence
      SET(DEFAULT ${TPL_ENABLE_${PARSED_TRIBITS}})
    ENDIF()
  ENDIF()

  MORPHEUS_ENABLE_OPTION(${PKG} ${DEFAULT} "Whether to enable the ${PKG} library")
  MORPHEUS_OPTION(${PKG}_DIR "" PATH "Location of ${PKG} library")
  SET(MORPHEUS_ENABLE_${PKG} ${MORPHEUS_ENABLE_${PKG}} PARENT_SCOPE)
  SET(MORPHEUS_${PKG}_DIR  ${MORPHEUS_${PKG}_DIR} PARENT_SCOPE)
ENDFUNCTION()

MORPHEUS_TPL_OPTION(CUDA    ${Morpheus_ENABLE_CUDA} CUDA)

IF(MORPHEUS_ENABLE_HIP AND NOT MORPHEUS_CXX_COMPILER_ID STREQUAL HIPCC)
  SET(ROCM_DEFAULT ON)
ELSE()
  SET(ROCM_DEFAULT OFF)
ENDIF()
MORPHEUS_TPL_OPTION(ROCM    ${ROCM_DEFAULT})

MORPHEUS_IMPORT_TPL(CUDA INTERFACE)
MORPHEUS_IMPORT_TPL(ROCM INTERFACE)

#Convert list to newlines (which CMake doesn't always like in cache variables)
STRING(REPLACE ";" "\n" MORPHEUS_TPL_EXPORT_TEMP "${KOKKOS_TPL_EXPORTS}")
#Convert to a regular variable
UNSET(MORPHEUS_TPL_EXPORTS CACHE)
SET(MORPHEUS_TPL_EXPORTS ${MORPHEUS_TPL_EXPORT_TEMP})
